Configure shared StyleCop ruleset and implement most suggestions
jobbrIO/jobbr-server pull request #92
Opened 2022-12-30 14:41 UTC by RKivioja

2022-12-30 14:58 UTC, RKivioja commented
Waits for the "devsupport" target change from "net6.0" to "netstandard2.0".

2023-01-03 13:10 UTC, RKivioja commented
@eXpl0it3r This should be fine now.

2023-01-03 13:46 UTC, eXpl0it3r requested changes

2023-01-03 13:46 UTC, eXpl0it3r commented on source/Jobbr.Server.UnitTests/Jobbr.Server.UnitTests.csproj
> +        <TargetFrameworks>net6.0</TargetFrameworks>
Should be singular, as we don't multi-target

2023-01-03 13:46 UTC, eXpl0it3r commented on source/Jobbr.Server/Scheduling/DefaultScheduler.cs
> +        private List<ScheduledPlanItem> _currentPlan = new List<ScheduledPlanItem>();
The previous "default" initialization would also be okay for me

2023-01-03 15:07 UTC, eXpl0it3r approved these changes

2023-01-03 15:12 UTC, merged